### ISSUE TITLE
Add support to ad-hoc piwik server

### ISSUE THREAD

**Issue by filhocf** [sualko/owncloud_piwik#5]
Hi

I have a central piwik server and wish to add my owncloud server in it. 

In other hand, is a good thing (IMHO) to add a field where you can set if wish http or https. I tried to use "http://my_internal_piwik_server/piwik" instead of "//my_internal_piwik_server/piwik", but without success.

Anyway, congratulation by your iniciative.

Regards,
Claudio Ferreira

**Comment by sualko** [comment]
<code>//my_internal_piwik_server/piwik</code> should choose either https or http, depending on which channel (https(s)) do you visit your owncloud installation.

I am not sure what you mean with "ad-hoc server", but if you wish to use a server on a different domain as your oc installation you have to use a proxy (e.g. /piwik/ -> https://your-domain/), because of oc's content security policy (csp).

**Comment by filhocf** [comment]
Thank you, Sualko.

About my piwik server, i have one machine only for it, and other for oc. So, i added my oc site in piwik and installed your app in my oc's env, each with your own IP. If i understood correctly, you are speaking that i need to use a proxy to do my oc "speak" with my piwik because oc blocks js like of piwik by security. Where, in oc, can i set this proxy? Sorry, but i am the man of piwik, and not of oc.

Thanks in advanced,
Claudio

**Comment by sualko** [comment]
It is not either about oc or piwik. It is about webserver and web 
technologies. But it is right what you said. You need a proxy from your oc 
domain to piwik. For apache search for mod_proxy. Hopefully this helps you 
a little bit.
